=== alx71hub/hcb/bnf.xsd
<?xml version='1.0' encoding="utf-8"?>
<xsd:schema
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://www.w3.org/2001/XMLSchema
                      http://www.w3.org/2001/XMLSchema.xsd'
  xmlns:xsd='http://www.w3.org/2001/XMLSchema'>

  <xsd:element name='bnf' type='BNFType'/>

  <xsd:complexType name='BNFType'>
    <xsd:sequence>
      <xsd:element name='section' type='SectionType' maxOccurs='unbounded'/>
    </xsd:sequence>
    <xsd:attribute name='version' type='VersionType' use='required'/>
    <xsd:attribute name='update' type='DateType' use='required'/>
  </xsd:complexType>

  <xsd:simpleType name='VersionType'>
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='\d+\.\d+'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name='DateType'>
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='[1-3]?\d-[A-Z][a-z][a-z]-\d\d\d\d'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name='SectionType'>
    <xsd:sequence>
      <xsd:element name='rule' type='RuleType' maxOccurs='unbounded'/>
    </xsd:sequence>
    <xsd:attribute name='id' type='SectionIDType' use='required'/>
  </xsd:complexType>

  <xsd:simpleType name='SectionIDType'>
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='[a-z]+(\.[a-z]+)*'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name='RuleType'>
    <xsd:sequence>
      <xsd:element name='syntax' type='NonTerminalNameType'/>
      <xsd:element name='sequence' type='SequenceType'/>
    </xsd:sequence>
    <xsd:attribute name='issue' type='xsd:unsignedShort' use='optional'/>
  </xsd:complexType>

  <xsd:simpleType name='NonTerminalNameType'>
    <xsd:restriction base='xsd:string'>
      <xsd:pattern value='([_a-z])+(\-[_a-z]+)*'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name='SequenceType'>
    <xsd:sequence>
      <xsd:element name='alternative' type='AlternativeType' maxOccurs='unbounded'/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name='AlternativeType'>
    <xsd:choice maxOccurs='unbounded'>
      <xsd:element name='terminal' type='TerminalType'/>
      <xsd:element name='non-terminal' type='NonTerminalType'/>
    </xsd:choice>
    <xsd:attribute name='issue' type='xsd:unsignedShort' use='optional'/>
    <xsd:attribute name='note' type='xsd:string' use='optional'/>
  </xsd:complexType>

  <xsd:simpleType name='BooleanType'>
    <xsd:restriction base='xsd:string'>
      <xsd:enumeration value='true'/>
      <xsd:enumeration value='false'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name='TerminalType'>
    <xsd:simpleContent>
      <xsd:extension base='xsd:string'>
        <xsd:attribute name='optional' type='BooleanType' default='false'/>
        <xsd:attribute name='sentence' type='BooleanType' default='false'/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name='NonTerminalType'>
    <xsd:simpleContent>
      <xsd:extension base='NonTerminalNameType'>
        <xsd:attribute name='optional' type='BooleanType' default='false'/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

</xsd:schema>

=== alx71hub/hcb/bnf.xml
<?xml version="1.0" encoding="UTF-8"?>
<bnf
  version="3.5"
  update="10-Aug-2021"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="bnf.xsd">

<section id="lex.charset">
  <rule>
    <syntax>hex-quad</syntax>
    <sequence>
      <alternative>
        <non-terminal>hexadecimal-digit</non-terminal>
        <non-terminal>hexadecimal-digit</non-terminal>
        <non-terminal>hexadecimal-digit</non-terminal>
        <non-terminal>hexadecimal-digit</non-terminal>
      </alternative>
    </sequence>
  </rule>
  <rule>
    <syntax>universal-character-name</syntax>
    <sequence>
      <alternative>
        <terminal>\u</terminal>
        <non-terminal>hex-quad</non-terminal>
      </alternative>
      <alternative>
        <terminal>\U</terminal>
        <non-terminal>hex-quad</non-terminal>
        <non-terminal>hex-quad</non-terminal>
      </alternative>
    </sequence>
  </rule>
</section>

<section id="lex.pptoken">
  <rule>
    <syntax>preprocessing-token</syntax>
    <sequence>
      <alternative>
        <non-terminal>header-name</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>identifier</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>pp-number</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>character-literal</non-terminal>
      </alternative>
      <alternative note="C++0x">
        <non-terminal>user-defined-character-literal</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>string-literal</non-terminal>
      </alternative>
      <alternative note="C++0x">
        <non-terminal>user-defined-string-literal</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>preprocessing-op-or-punc</non-terminal>
      </alternative>
      <alternative>
        <terminal sentence="true">each non-white-space character that cannot be one of the above</terminal>
      </alternative>
    </sequence>
  </rule>
</section>

<section id="lex.token">
  <rule>
    <syntax>token</syntax>
    <sequence>
      <alternative>
        <non-terminal>identifier</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>keyword</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>literal</non-terminal>
      </alternative>
      <alternative issue="189">
        <non-terminal>operator-token</non-terminal>
      </alternative>
      <alternative issue="189">
        <non-terminal>punctuator</non-terminal>
      </alternative>
    </sequence>
  </rule>
</section>

<section id="lex.header">
  <rule>
    <syntax>header-name</syntax>
    <sequence>
      <alternative>
        <terminal>&lt;</terminal>
        <non-terminal>h-char-sequence</non-terminal>
        <terminal>></terminal>
      </alternative>
      <alternative>
        <terminal>"</terminal>
        <non-terminal>q-char-sequence</non-terminal>
        <terminal>"</terminal>
      </alternative>
    </sequence>
  </rule>
  <rule>
    <syntax>h-char-sequence</syntax>
    <sequence>
    <alternative>
      <non-terminal>h-char</non-terminal>
    </alternative>
    <alternative>
      <non-terminal>h-char-sequence</non-terminal>
      <non-terminal>h-char</non-terminal>
    </alternative>
    </sequence>
  </rule>
  <rule>
    <syntax>h-char</syntax>
    <sequence>
    <alternative>
      <terminal sentence="true">any member of the source character set except new-line and ></terminal>
    </alternative>
    </sequence>
  </rule>
  <rule>
    <syntax>q-char-sequence</syntax>
    <sequence>
    <alternative>
      <non-terminal>q-char</non-terminal>
    </alternative>
    <alternative>
      <non-terminal>q-char-sequence</non-terminal>
      <non-terminal>q-char</non-terminal>
    </alternative>
    </sequence>
  </rule>
  <rule>
    <syntax>q-char</syntax>
    <sequence>
    <alternative>
      <terminal sentence="true">any member of the source character set except new-line and "</terminal>
    </alternative>
    </sequence>
  </rule>
</section>

<section id="lex.ppnumber">
  <rule>
    <syntax>pp-number</syntax>
    <sequence>
      <alternative>
        <non-terminal>digit</non-terminal>
      </alternative>
      <alternative>
        <terminal>.</terminal>
        <non-terminal>digit</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>pp-number</non-terminal>
        <non-terminal>digit</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>pp-number</non-terminal>
        <non-terminal>identifier-nondigit</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>pp-number</non-terminal>
        <terminal>e</terminal>
        <non-terminal>sign</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>pp-number</non-terminal>
        <terminal>E</terminal>
        <non-terminal>sign</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>pp-number</non-terminal>
        <terminal>.</terminal>
      </alternative>
    </sequence>
  </rule>
</section>

<section id="lex.name">
  <rule>
    <syntax>identifier</syntax>
    <sequence>
      <alternative note="C++0x">
        <non-terminal>identifier-nondigit</non-terminal>
      </alternative>
      <alternative note="C++0x">
        <non-terminal>identifier</non-terminal>
        <non-terminal>identifier-nondigit</non-terminal>
      </alternative>
      <alternative>
        <non-terminal>identifier</non-terminal>
        <non-terminal>digit</non-terminal>
      </alternative>
    </sequence>
  </rule>
  <rule>
    <syntax>identifier-nondigit</syntax>
    <sequence>
      <alternative note="C++0x">
        <non-terminal>nondigit</non-terminal>
      </alternative>
      <alternative note="C++0x">
        <non-terminal>universal-character-name</non-terminal>
      </alternative>
      <alternative note="C++0x">
        <terminal sentence="true">other implementation-defined characters</terminal>
      </alternative>
    </sequence>
  </rule>
  <rule>
    <syntax>nondigit</syntax>
    <sequence>
      <alternative note="Removed in C++0x">
        <terminal>universal-character-name</terminal>
      </alternative>
      <alternative>
        <terminal>a</terminal>
      </alternative>
      <alternative>
        <terminal>b</terminal>
      </alternative>
      <alternative>
        <terminal>c</terminal>
      </alternative>
      <alternative>
        <terminal>d</terminal>
      </alternative>
      <alternative>
        <terminal>e</terminal>
      </alternative>
      <alternative>
        <terminal>f</terminal>
      </alternative>
      <alternative>
        <terminal>g</terminal>
      </alternative>
      <alternative>
        <terminal>h</terminal>
      </alternative>
      <alternative>
        <terminal>i</terminal>
      </alternative>
      <alternative>
        <terminal>j</terminal>
      </alternative>
      <alternative>
        <terminal>k</terminal>
      </alternative>
      <alternative>
        <terminal>l</terminal>
      </alternative>
      <alternative>
        <terminal>m</terminal>
      </alternative>
      <alternative>
        <terminal>n</terminal>
      </alternative>
      <alternative>
        <terminal>o</terminal>
      </alternative>
      <alternative>
        <terminal>p</terminal>
      </alternative>
      <alternative>
        <terminal>q</terminal>
      </alternative>
      <alternative>
        <terminal>r</terminal>
      </alternative>
      <alternative>
        <terminal>s</terminal>
      </alternative>
      <alternative>
        <terminal>t</terminal>
      </alternative>
      <alternative>
        <terminal>u</terminal>
      </alternative>
      <alternative>
        <terminal>v</terminal>
      </alternative>
      <alternative>
        <terminal>w</terminal>
      </alternative>
      <alternative>
        <terminal>x</terminal>
      </alternative>
      <alternative>
        <terminal>y</terminal>
      </alternative>
      <alternative>
        <terminal>z</terminal>
      </alternative>
      <alternative>
        <terminal>A</terminal>
      </alternative>
      <alternative>
        <terminal>B</terminal>
      </alternative>
      <alternative>
        <terminal>C</terminal>
      </alternative>
      <alternative>
        <terminal>D</terminal>
      </alternative>
      <alternative>
        <terminal>E</terminal>
      </alternative>
      <alternative>
        <terminal>F</terminal>
      </alternative>
      <alternative>
        <terminal>G</terminal>
      </alternative>
      <alternative>
        <terminal>H</terminal>
      </alternative>
      <alternative>
        <terminal>I</terminal>
      </alternative>
      <alternative>
        <terminal>J</terminal>
      </alternative>
      <alternative>
        <terminal>K</terminal>
      </alternative>
      <alternative>
        <terminal>L</terminal>
      </alternative>
      <alternative>
        <terminal>M</terminal>
      </alternative>
      <alternative>
        <terminal>N</terminal>
      </alternative>
      <alternative>
        <terminal>O</terminal>
      </alternative>
      <alternative>
        <terminal>P</terminal>
      </alternative>
      <alternative>
        <terminal>Q</terminal>
      </alternative>
      <alternative>
        <terminal>R</terminal>
      </alternative>
      <alternative>
        <terminal>S</terminal>
      </alternative>
      <alternative>
        <terminal>T</terminal>
      </alternative>
      <alternative>
        <terminal>U</terminal>
      </alternative>
      <alternative>
        <terminal>V</terminal>
      </alternative>
      <alternative>
        <terminal>W</terminal>
      </alternative>
      <alternative>
        <terminal>X</terminal>
      </alternative>
      <alternative>
        <terminal>Y</terminal>
      </alternative>
      <alternative>
        <terminal>Z</terminal>
      </alternative>
